import Head from 'next/head'
import { Inter } from '@next/font/google'
//import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Carousel } from '#/components/ui/carousel'

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex-1 flex bg-gradient-to-t from-[#accbee] to-[#e7f0fd] justify-center items-center" >
        <Carousel>
          <div className='carousel-card'>
            <div className="ribbon ribbon-top-left"><span>about me</span></div>
          </div>
          <div className='carousel-card'>
            <div className="ribbon ribbon-top-left"><span>contact</span></div>
          </div>
          <div className='carousel-card'>
            <div className="ribbon ribbon-top-left"><span>favorvites</span></div>
          </div>
          <div className='carousel-card'>
            <div className="ribbon ribbon-top-left"><span>life</span></div>
          </div> 
        </Carousel>

      </div>
    </>
  )
}
